### PR TITLE
[WIP]: Balancer Ethereum Implementation

### LINKED ISSUE #15: Add Defitrack support for Balancer V2 [Ethereum Mainnet]
Cfr Balancer on Polygon

Subgraph to pull data from:
https://thegraph.com/hosted-service/subgraph/messari/balancer-v2-ethereum

General graph data should be added as:

**defitrack-protocols** -> **balancer** -> **BalancerEthereumService**

## Pooling Market Support

all pooling markets should become available.

## User Pooling Support

It should be possible to query for user balances in balancer v2 pools.

### PR DESCRIPTION
**Pull request by mul1sh**
Will fix #15

### CODE REVIEW

**Comment by TheMoneyLisa** [comment]
Hi @mul1sh, great to see you are working on this. Did you ping messari about the failing graph? If not, I can contact them to request a fix.

**Comment by mul1sh** [comment]
> Hi @mul1sh, great to see you are working on this. Did you ping messari about the failing graph? If not, I can contact them to request a fix.

Not yet because I don’t know how to reach them. So yeah I would appreciate it very much if you would contact them to fix it, so that I sort this issue asap 🙂

**Comment by TheMoneyLisa** [comment]
The graph is synced now.

**Comment by mul1sh** [comment]
> The graph is synced now. Be sure to merge **main** into your current working branch. A lot of structural changes have happend in the meantime.

Ok thanks for heads up, will do 🙂

**Comment by TheMoneyLisa** [comment]
Just wanted to check up on your progress. How are things going? Let us know if you're stuck somewhere :).

**Comment by mul1sh** [comment]
> Just wanted to check up on your progress. How are things going? Let us know if you're stuck somewhere :).

Sorry been a bit caught up on my end, kindly give me till tomorrow and I'll do the final submission :)

**Comment by TheMoneyLisa** [comment]
Take your time :). We've also added a new section on https://docs.defitrack.io specifically targeting new contributors. Feel free to check it out or reach out if you have any questions.

**Comment by mul1sh** [comment]
> Take your time :). We've also added a new section on https://docs.defitrack.io specifically targeting new contributors. Feel free to check it out or reach out if you have any questions.

Ok thanks for notifying me, will do 😃

**Comment by mul1sh** [comment]
@TheMoneyLisa It seems the query data returned by the messari subgraph is quite different from the expected data in the `PoolShare` data models. So should I run the liquidity pool queries separately and then aggregate the data in a different function so that they match the `PoolShare` or should I create a new data model and if so which fields should I include?

**Comment by TheMoneyLisa** [comment]
You can create a new data model depending on the data you get from the graph api. Everything in the **balancer** module can be specific to balancer. 

The only domain models that are predefined are the ones defined [here](https://docs.defitrack.io/developers/domain-model), as well as the (still undocumented ones) related to positions.

**Comment by TheMoneyLisa** [comment]
Let me know if you have any additional questions! :D

**Comment by mul1sh** [comment]
> Let me know if you have any additional questions! :D

Will do, just been learning the messari balancer subgraph abit better, will submit a PR by the very latest Tuesday morning

**Comment by TheMoneyLisa** [comment]
Take your time, no rush :D

**Comment by mul1sh** [comment]
> Take your time, no rush :D

Sorry @TheMoneyLisa I got caught up again 😬 , will definitely finish tomorrow no more delays

**Comment by mul1sh** [comment]
Just 1 more commit in a few hours and I'll be done 😄

**Pull request closed without merging**
